export const experiences = [
  {
    id: 0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSr8l9vO77O-94XRgczw61wd70VoGXdpK25iQ&s",
    role: "Data Analyst / Data Scientist",
    company: "Freelance",
    date: "May 2025 - Present",
    desc: "As a Freelance Data Analyst and Data Scientist, I delivered end-to-end analytics and machine learning solutions for multiple clients across business and digital domains. I built and deployed predictive and classification models using Python (Pandas, NumPy, Scikit-learn) and SQL/NoSQL databases to forecast user behavior, improving conversion rates by up to 60%. I also designed scalable ETL pipelines across multi-source datasets, reducing data processing time by 35% and improving data reliability for reporting and analytics.",
    skills: [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "SQL",
      "NoSQL",
      "Machine Learning",
      "Predictive Modeling",
      "ETL Pipelines",
      "Data Analysis",
    ],
  },
  {
    id: 1,
    img: "https://media.licdn.com/dms/image/v2/C560BAQGCs07yzlcG9Q/company-logo_200_200/company-logo_200_200/0/1630646786601/nullclassdotcom_logo?e=2147483647&v=beta&t=HzWjQJIPj_5_S7_jDDEjZ2yeQpYkoZnMDpLs7cw1zqQ",
    role: "Data Analyst Intern",
    company: "NullClass",
    date: "Dec 2024 - Mar 2025",
    desc: "As a Data Analyst Intern at NullClass, I designed and developed interactive Tableau dashboards to monitor KPIs, user activity, job postings, and engagement metrics, improving reporting efficiency by 40%. I performed sentiment analysis, text mining, and predictive analytics on large-scale Twitter datasets using Python (Pandas, NumPy), enhancing the accuracy of targeted marketing campaigns by 20%. Additionally, I engineered data models and automated data preparation workflows using SQL, reducing manual reporting efforts by 30% and improving data consistency.",
    skills: [
      "Tableau",
      "Python",
      "Pandas",
      "NumPy",
      "SQL",
      "Data Modeling",
      "Sentiment Analysis",
      "Predictive Analytics",
      "Data Visualization",
      "KPI Tracking",
    ],
  },
  {
    id: 2,
    img: "https://media.licdn.com/dms/image/v2/D560BAQHDmIfYA5sY7w/company-logo_200_200/company-logo_200_200/0/1685777115831?e=2147483647&v=beta&t=BrbAEJ0lciXi69uR0VBVOdOGHno8XzclslDmxrVYaNI",
    role: "Data Science Intern",
    company: "CodSoft",
    date: "Sep 2024 - Nov 2024",
    desc: "At CodSoft, I cleaned, transformed, and modeled datasets using Power Query, Power BI, and Excel, resulting in a 30% improvement in analytical depth for internal product reporting. I built 5+ interactive Power BI dashboards with custom DAX calculations, KPIs, and drill-through reports to support product and business teams. I also performed exploratory data analysis (EDA), correlation analysis, and feature engineering across 10+ variables to enable data-driven business and product decisions.",
    skills: [
      "Power BI",
      "Excel",
      "Power Query",
      "DAX",
      "EDA",
      "Feature Engineering",
      "Data Modeling",
      "Statistical Analysis",
      "Dashboard Development",
      "Data Visualization",
    ],
  },
];
