export const experiences = [
  {
    id: 0,
    img: "https://media.licdn.com/dms/image/v2/C560BAQGCs07yzlcG9Q/company-logo_200_200/company-logo_200_200/0/1630646786601/nullclassdotcom_logo?e=2147483647&v=beta&t=HzWjQJIPj_5_S7_jDDEjZ2yeQpYkoZnMDpLs7cw1zqQ",
    role: "Data Analyst Intern",
    company: "NullClass",
    date: "Dec 2024 - Feb 2025",
    desc: "As a Data Analyst Intern at NullClass, I designed and developed interactive Tableau dashboards to track key performance indicators (KPIs), user engagement, and job portal trends, which improved real-time reporting efficiency by 30%. I worked with large-scale Twitter datasets using Python (Pandas, NumPy) to perform sentiment analysis and uncover actionable insights, contributing to a 20% increase in the effectiveness of targeted marketing campaigns. Additionally, I applied SQL and Python for data cleaning and transformation, reducing data processing time by 25% and ensuring high data accuracy and integrity.",
    skills: [
      "Tableau",
      "Python",
      "Pandas",
      "NumPy",
      "SQL",
      "Data Cleaning",
      "Sentiment Analysis",
      "Data Visualization",
      "KPI Tracking",
      "Dashboard Development",
    ],
  },
  {
    id: 0,
    img: "https://media.licdn.com/dms/image/v2/D560BAQHDmIfYA5sY7w/company-logo_200_200/company-logo_200_200/0/1685777115831?e=2147483647&v=beta&t=BrbAEJ0lciXi69uR0VBVOdOGHno8XzclslDmxrVYaNI",
    role: "Data Science Intern",
    company: "CodSoft",
    date: "Sep 2024 - Oct 2024",
    desc: "At CodSoft, I focused on data preparation and visualization using Excel, Power Query, and Power BI, ensuring 100% data accuracy across multiple dashboards. I developed over five interactive dashboards to support data-driven decision-making. By implementing data modeling techniques, I established logical relationships across more than 10 attributes, deepening analytical insights by 30%. I also performed descriptive analytics using DAX, enabling complex trend analysis and real-time computations that improved data processing efficiency by 25%.",
    skills: [
      "Power BI",
      "Excel",
      "Power Query",
      "DAX",
      "Data Modeling",
      "Data Cleaning",
      "Dashboard Design",
      "Descriptive Analytics",
      "Statistical Analysis",
      "Data Visualization",
    ],
  },
  {
    id: 3,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSr8l9vO77O-94XRgczw61wd70VoGXdpK25iQ&s",
    role: "Freelance Designer",
    company: "Freelance",
    date: "Sep 2023 - Dec 2023",
    desc: "As a Freelance Designer and Content Writer, I created visually engaging designs using Canva and crafted clear, audience-focused content for websites, blogs, and social media—helping clients communicate effectively and elevate their presence.",
    skills: ["Graphic Design", "Content Writing"],
  },
];
